### ISSUE TITLE
remove .html from URLs

### ISSUE THREAD

**Issue by JosephMcArthur** [emckiernan/whyopenresearch#5]

**Comment by Mahdisadjadi** [comment]
Github can already show pages with no `html` extension. For example, this works:

[Increase your visibility](http://whyopenresearch.org/visibility)

but `html` should be removed in all links in `<a href>` within pages!

**Comment by emckiernan** [comment]
Great, thank you! Will make this change ASAP.

**Comment by Mahdisadjadi** [comment]
I did a pull request #9. Hopefully, it fixes this issue!

**Comment by emckiernan** [comment]
Thanks for your help! Unfortunately, I tried to merge your changes but found several conflicts I couldn't resolve, as well as several pages that seemed to have lost links (404s). So, I went ahead and made changes manually instead.
